coverage:
  precision: 2
  round: down
  range: "90...100"
  ignore:
    - CoinbaseProTests/*
    - App/*
  status:
    patch:
      default:
        threshold: 50
        if_no_uploads: error
    changes: true
    project:
      default:
        target: auto
        threshold: 2
        if_no_uploads: error
comment: false
